### ISSUE TITLE
Exception when project has no timers

### ISSUE THREAD

**Issue by lcx** [timcraft/noko#6]
A call to GET /v2/projects/:project_id/timer will return a 404 if the project currently has no timers according to the API docs: https://developer.nokotime.com/v2/timers/#get-a-projects-timer 
unfortunately noko gem raises an exception 

```
Noko::Error (unexpected 404 response from api.nokotime.com)
```

https://github.com/timcraft/noko/blob/66fedd8b1d12400b5e6ac1a8d126ad7edd312e03/lib/noko/client.rb#L79

it should however return something instead of an exception as it's expected behaviour. Not sure what would make sense here. nil? empty array?

**Comment by timcraft** [comment]
Sorry for not responding to this sooner, life happened.

Raising 4xx error responses as exceptions is intentional, I've found that the easiest approach to work with generally. Nils or empty arrays could be confusing in their own ways.

A generic `Noko::Error` isn't very helpful or easy to figure out though. I've released v1.6.0 which adds `Noko::NotFound`, `Noko::ClientError`, and `Noko::ServerError` exceptions. So you should now be able to `rescue Noko::NotFound` and implement whatever logic you need there.
